---
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "05:55"
    open-pull-requests-limit: 5
    reviewers:
      - skarzi
    commit-message:
      prefix: "build(deps): "
      prefix-development: "chore(deps): "
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "05:55"
    open-pull-requests-limit: 1
    reviewers:
      - skarzi
    commit-message:
      prefix: "chore(deps): "
