---
name: misspell
'on':
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sobolevn/misspell-fixer-action@master
      - uses: peter-evans/create-pull-request@v4.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'fix: fix typos with misspell-fixer'
          title: 'fix: fix typos with misspell-fixer'
          branch: fix/misspell-fixer/typos
          delete-branch: true
          reviewers: skarzi
